#!/usr/bin/env bash

set -e

cp ./git/gitconfig ~/.gitconfig
cp ./git/gitignore ~/.gitignore

cp ./.hushlogin ~/.hushlogin
cp ./LICENSE.md ~/LICENSE.md

cp -R ./bin ~/bin

# Install Caddy to /usr/bin/caddy
curl https://getcaddy.com | bash

sh -c ./zsh/install
sh -c ./brew/install
sh -c ./mac/setup-defaults
sh -c ./node/install
sh -c ./node/yarn